### ISSUE TITLE
Dataset Merging Bug

### ISSUE THREAD

**Issue by coreyostrove** [sandialabs/pyGSTi#340]
When trying to add additional counts from one dataset to another, using any of the various `add_*` methods of the DataSet object an error is raised when trying to do so with aggregation of counts for common circuits. Below is a minimal working example of this using the `add_counts_from_dataset` method, but the same error is encountered using other methods as well (they all seem to eventually make use of the `_add_raw_arrays` which is where the error is encountered. This looks to be an issue with the fact that the aggregation is performed by concatenation of the `oliData` arrays (and other similarly structured arrays) for each data set. This is fine when aggregating oliData for data sets with shots recorded as clickstreams, or when the circuit being added is new, but doesn't work as expected when the oliData corresponds to the outcome labels for collected numbers of shots. 
```
import pygsti
from pygsti.data.datasetconstruction import simulate_data
from pygsti.modelpacks import smq1Q_XY
target_model = smq1Q_XY.target_model('full TP')
circuits = smq1Q_XY.create_gst_experiment_design(1)
ds1 = simulate_data(target_model, circuits.all_circuits_needing_data, num_samples=10)
ds2 = simulate_data(target_model, circuits.all_circuits_needing_data, num_samples=10)
print(ds1.collisionAction)
print(ds1.bStatic)
ds1.bStatic= False
ds1.add_counts_from_dataset(ds2)
```
The resulting traceback is:

> 
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> Cell In[8], line 1
> ----> 1 ds1.add_counts_from_dataset(ds2)
> 
> File ~\Documents\pyGSTi_master_branch\pygsti\data\dataset.py:2102, in DataSet.add_counts_from_dataset(self, other_data_set)
>    2089 def add_counts_from_dataset(self, other_data_set):
>    2090     """
>    2091     Append another DataSet's data to this DataSet
>    2092 
>    (...)
>    2100     None
>    2101     """
> -> 2102     return self.add_series_from_dataset(other_data_set)
> 
> File ~\Documents\pyGSTi_master_branch\pygsti\data\dataset.py:2119, in DataSet.add_series_from_dataset(self, other_data_set)
>    2117 if self.bStatic: raise ValueError("Cannot add data to a static DataSet object")
>    2118 for circuit, dsRow in other_data_set.items():
> -> 2119     self.add_raw_series_data(circuit, dsRow.outcomes, dsRow.time, dsRow.reps, False)
> 
> File ~\Documents\pyGSTi_master_branch\pygsti\data\dataset.py:1714, in DataSet.add_raw_series_data(self, circuit, outcome_label_list, time_stamp_list, rep_count_list, overwrite_existing, record_zero_counts, aux, update_ol, unsafe)
>    1711 else:
>    1712     repArray = None
> -> 1714 self._add_raw_arrays(circuit, oliArray, timeArray, repArray,
>    1715                      overwrite_existing, record_zero_counts, aux)
> 
> File ~\Documents\pyGSTi_master_branch\pygsti\data\dataset.py:1745, in DataSet._add_raw_arrays(self, circuit, oli_array, time_array, rep_array, overwrite_existing, record_zero_counts, aux)
>    1743     if rep_array is not None: self.repData[circuitIndx] = rep_array
>    1744 else:
> -> 1745     self.oliData[circuitIndx] = _np.concatenate((self.oliData[circuitIndx], oli_array))
>    1746     self.timeData[circuitIndx] = _np.concatenate((self.timeData[circuitIndx], time_array))
>    1747     if rep_array is not None:
> 
> ValueError: could not broadcast input array from shape (4,) into shape (2,)

**Comment by sserita** [comment]
Hey @coreyostrove thanks for bringing this up! One question: Do you have a slightly less MWE where you run into this?

I'll note that I can make a version of this work by using `copy_nonstatic()` instead of setting the `bStatic` flag, as below. There are several differences between static and non-static DataSets, one of which is that the `cirIndex` array values are stored as slices in the static case and integer values for the non-static case. It appears that the concatenation code here functions properly when the DataSet is migrated more completely to a non-static one, but not when `circuitIndx` is a slice like it is in the static case.

```
from pygsti.data.datasetconstruction import simulate_data
from pygsti.modelpacks import smq1Q_XY
target_model = smq1Q_XY.target_model('full TP')
circuits = smq1Q_XY.create_gst_experiment_design(1)
ds1 = simulate_data(target_model, circuits.all_circuits_needing_data, num_samples=10)
ds2 = simulate_data(target_model, circuits.all_circuits_needing_data, num_samples=10)

ds3 = ds1.copy_nonstatic()
ds3.add_counts_from_dataset(ds2)
```

Assuming this is an issue somewhere else in the code, we can similarly fix it by using `copy_nonstatic()` there. Otherwise, maybe we should increase the documentation around this and/or remove the ability for `bStatic` to be modified by itself and add additional checks when we detect the user is trying to do this sort of thing without realizing they need a nonstatic version? Perhaps the `bStatic` asserts should mention `copy_nonstatic()` for example.
