### ISSUE TITLE
Indication of table caption in reports

### ISSUE THREAD

**Issue by juangmendoza19** [sandialabs/pyGSTi#416]
After many months utilizing pyGSTi reports, I just noticed that all table names can be clicked to display information about said table!

There is nothing indicating that these titles can be clicked. I would suggest some sort of information/arrow button. This is valuable information that many of our users may not have any idea exists.

**Comment by sserita** [comment]
This is fixed in [1114839](https://github.com/sandialabs/pyGSTi/commit/1114839e0592acfcea8f44afc58ee6ce6b391cc9). There is now a subcaption that says (Click to expand details) that is replaced with the caption details upon click.


Unclicked:
![Image](https://github.com/sandialabs/pyGSTi/assets/72409998/c4ccda04-14c9-4271-8a4e-cd184f4de157)


Clicked:
![Image](https://github.com/sandialabs/pyGSTi/assets/72409998/e49f7995-f024-4f7c-a7be-d845b26a3a58)
